name: ci

permissions:
  contents: read
  checks: write

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: '${{ matrix.os }}-latest'

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        node: [ 14, 16, 18, 20 ]
        exclude:
          - os: macos
            node: 14

    env:
      FORCE_COLOR: 1

    name: Node ${{ matrix.node }} on ${{ matrix.os }}

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
        continue-on-error: ${{ matrix.os == 'windows' }}
